language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_629ea2ee8b2a_key -iv $encrypted_629ea2ee8b2a_iv
  -in src/main/resources/application.properties.enc -out src/main/resources/application.properties -d
