language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_edeed057e1d6_key -iv $encrypted_edeed057e1d6_iv
  -in application.properties.enc -out src/main/resources/application.properties -d
