language: java
jdk:
- oraclejdk8
before_install:
- openssl aes-256-cbc -K $encrypted_40dfbfecac2f_key -iv $encrypted_40dfbfecac2f_iv
  -in application.properties.enc -out .\\application.properties -d
